version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file samTemplate.yml --s3-bucket test-bucket-rs3986 --output-template-file outputsamtemplate.yml
artifacts:
  type: zip
  files:
    - samTemplate.yml
    - outputsamtemplate.yml
