AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: CFT2LF1
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./hw3LF1.py
      Description: 'Lambda function for CP Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::671455739102:role/super'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: us-east-1

       
